set nocompatible
set nobackup
set noswapfile
set backspace=indent,eol,start

syntax on
filetype plugin on
filetype plugin indent on

set number
set ruler
set visualbell
set encoding=utf-8
set wrap
set textwidth=79
set formatoptions=tcqrn1

set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noshiftround

""""""""""""""""""""""""""""""""""""""""""""""""""""""
"     vim plug
""""""""""""""""""""""""""""""""""""""""""""""""""""""
if empty(glob("~/.vim/autoload/plug.vim"))
  :echom 'VIM Plug not found!'
  :echom 'Make sure the following path exists: ~/.vim/autoload/plug.vim'
else
  call plug#begin('~/.vim/plugged')
  Plug 'bling/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  Plug 'tomasiser/vim-code-dark'
  Plug 'scrooloose/nerdtree'
  Plug 'scrooloose/nerdcommenter'
  Plug 'tpope/vim-surround'
  Plug 'alvan/vim-closetag'
  Plug 'raimondi/delimitmate'
  call plug#end()

  autocmd vimenter * NERDTree               "show tree on startup
  let NERDTreeShowHidden=1                  "show hidden files
  let g:closetag_filenames = "*.html,*.xml" "setup closetag plugin
  
  set guifont=Consolas:h14:cANSI
  set background=dark
  colorscheme codedark
endif "end of vim plug
