set nocompatible
set nobackup
set noswapfile
set backspace=indent,eol,start

syntax on
filetype plugin on
filetype plugin indent on

set number
set ruler
set visualbell
set encoding=utf-8
set wrap
set textwidth=79
set formatoptions=tcqrn1

set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noshiftround

""""""""""""""""""""""""""""""""""""""""""""""""""""""
"     vim plug
""""""""""""""""""""""""""""""""""""""""""""""""""""""
if empty(glob("~/.vim/autoload/plug.vim"))
  :echom 'VIM Plug not found!'
  :echom 'Make sure the following path exists: ~/.vim/autoload/plug.vim'
else
  source ~/.vim/autoload/plug.vim
  call plug#begin('~/.vim/plugged')
    
    "Airline
    Plug 'bling/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    
    "Colorschemes
    Plug 'jnurmine/zenburn'
    Plug 'morhetz/gruvbox'
    Plug 'tomasiser/vim-code-dark'
    "Plug 'altercation/vim-colors-solarized'
    "set rtp+=~/.vim/plugged/vim-colors-solarized

    "NERDTre
    Plug 'scrooloose/nerdtree'
    Plug 'scrooloose/nerdcommenter'

    "Code & Text
    Plug 'tpope/vim-surround'
    Plug 'alvan/vim-closetag'
    Plug 'raimondi/delimitmate'
  call plug#end()

""""""""""""""""""""""""""""""""""""""""""""""""""""""

  autocmd vimenter * NERDTree               "show tree on startup
  let NERDTreeShowHidden=1                  "show hidden files
  let g:closetag_filenames = "*.html,*.xml" "setup closetag plugin
  
  "Setup the colorscheme, font etc.
  set guifont=Consolas:h14:cANSI
  "set background=light
  let g:zenburn_high_Contrast=1
  colorscheme zenburn
endif "end of vim plug
